@AspNetCore.Auth_HostAddress = http://localhost:5120

GET {{AspNetCore.Auth_HostAddress}}/todos/
Accept: application/json

###

GET {{AspNetCore.Auth_HostAddress}}/todos/1
Accept: application/json

###
